/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.1.600
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BusinessClassification } from './businessClassification';
import { BusinessIndustry } from './businessIndustry';
import { BusinessRegionsOfOperation } from './businessRegionsOfOperation';
import { BusinessRegistrationIdentifier } from './businessRegistrationIdentifier';
import { BusinessStockExchanges } from './businessStockExchanges';
import { BusinessType } from './businessType';
import { JobPosition } from './jobPosition';

export class A2PApplicationSubmission {
    'isTwilioTermsRead': boolean;
    'isPrivacyPolicyOnWebsite': boolean;
    'isTosOnWebsite': boolean;
    'isStopUnderstood': boolean;
    'isManualRead': boolean;
    'isCtiaShortCodeRead': boolean;
    'isStandardsUnderstood': boolean;
    'isShortCodeUnderstood': boolean;
    'isOptInOutUnderstood': boolean;
    'isShortCodeTransferUnderstood': boolean;
    'isPricingUnderstood': boolean;
    'isShortCodeTimelineUnderstood': boolean;
    'businessName': string;
    'businessType': BusinessType;
    'businessClassification': BusinessClassification;
    'businessIndustry': BusinessIndustry;
    'taxIDType': BusinessRegistrationIdentifier;
    'taxID': string;
    'websiteURL': string;
    'socialMediaURL': string;
    'regionsOfOperation': Array<BusinessRegionsOfOperation>;
    'stockExchange'?: BusinessStockExchanges;
    'stockTicker'?: string;
    'messagingVolumeHigh': boolean;
    'address1': string;
    'address2'?: string;
    'city': string;
    'state': string;
    'postalCode': string;
    'country': string;
    'firstName': string;
    'lastName': string;
    'email': string;
    'jobTitle': string;
    'jobPosition': JobPosition;
    'phoneNumber': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isTwilioTermsRead",
            "baseName": "isTwilioTermsRead",
            "type": "boolean"
        },
        {
            "name": "isPrivacyPolicyOnWebsite",
            "baseName": "isPrivacyPolicyOnWebsite",
            "type": "boolean"
        },
        {
            "name": "isTosOnWebsite",
            "baseName": "isTosOnWebsite",
            "type": "boolean"
        },
        {
            "name": "isStopUnderstood",
            "baseName": "isStopUnderstood",
            "type": "boolean"
        },
        {
            "name": "isManualRead",
            "baseName": "isManualRead",
            "type": "boolean"
        },
        {
            "name": "isCtiaShortCodeRead",
            "baseName": "isCtiaShortCodeRead",
            "type": "boolean"
        },
        {
            "name": "isStandardsUnderstood",
            "baseName": "isStandardsUnderstood",
            "type": "boolean"
        },
        {
            "name": "isShortCodeUnderstood",
            "baseName": "isShortCodeUnderstood",
            "type": "boolean"
        },
        {
            "name": "isOptInOutUnderstood",
            "baseName": "isOptInOutUnderstood",
            "type": "boolean"
        },
        {
            "name": "isShortCodeTransferUnderstood",
            "baseName": "isShortCodeTransferUnderstood",
            "type": "boolean"
        },
        {
            "name": "isPricingUnderstood",
            "baseName": "isPricingUnderstood",
            "type": "boolean"
        },
        {
            "name": "isShortCodeTimelineUnderstood",
            "baseName": "isShortCodeTimelineUnderstood",
            "type": "boolean"
        },
        {
            "name": "businessName",
            "baseName": "businessName",
            "type": "string"
        },
        {
            "name": "businessType",
            "baseName": "businessType",
            "type": "BusinessType"
        },
        {
            "name": "businessClassification",
            "baseName": "businessClassification",
            "type": "BusinessClassification"
        },
        {
            "name": "businessIndustry",
            "baseName": "businessIndustry",
            "type": "BusinessIndustry"
        },
        {
            "name": "taxIDType",
            "baseName": "taxIDType",
            "type": "BusinessRegistrationIdentifier"
        },
        {
            "name": "taxID",
            "baseName": "taxID",
            "type": "string"
        },
        {
            "name": "websiteURL",
            "baseName": "websiteURL",
            "type": "string"
        },
        {
            "name": "socialMediaURL",
            "baseName": "socialMediaURL",
            "type": "string"
        },
        {
            "name": "regionsOfOperation",
            "baseName": "regionsOfOperation",
            "type": "Array<BusinessRegionsOfOperation>"
        },
        {
            "name": "stockExchange",
            "baseName": "stockExchange",
            "type": "BusinessStockExchanges"
        },
        {
            "name": "stockTicker",
            "baseName": "stockTicker",
            "type": "string"
        },
        {
            "name": "messagingVolumeHigh",
            "baseName": "messagingVolumeHigh",
            "type": "boolean"
        },
        {
            "name": "address1",
            "baseName": "address1",
            "type": "string"
        },
        {
            "name": "address2",
            "baseName": "address2",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "string"
        },
        {
            "name": "jobPosition",
            "baseName": "jobPosition",
            "type": "JobPosition"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return A2PApplicationSubmission.attributeTypeMap;
    }
}

export namespace A2PApplicationSubmission {
}
