/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-17T02:55:26.052Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BusinessClassification } from './businessClassification';
import { BusinessIndustry } from './businessIndustry';
import { BusinessRegistrationIdentifier } from './businessRegistrationIdentifier';
import { BusinessStockExchanges } from './businessStockExchanges';
import { BusinessType } from './businessType';
import { JobPosition } from './jobPosition';

export class A2PApplicationSubmission extends null<String, any> {
    'isTwilioTermsRead': any | null;
    'isPrivacyPolicyOnWebsite': any | null;
    'isTosOnWebsite': any | null;
    'isStopUnderstood': any | null;
    'isManualRead': any | null;
    'isCtiaShortCodeRead': any | null;
    'isStandardsUnderstood': any | null;
    'isShortCodeUnderstood': any | null;
    'isOptInOutUnderstood': any | null;
    'isShortCodeTransferUnderstood': any | null;
    'isPricingUnderstood': any | null;
    'isShortCodeTimelineUnderstood': any | null;
    'businessName': any | null;
    'businessType': BusinessType;
    'businessClassification': BusinessClassification;
    'businessIndustry': BusinessIndustry;
    'taxIDType': BusinessRegistrationIdentifier;
    'taxID': any | null;
    'websiteURL': any | null;
    'socialMediaURL': any | null;
    'regionsOfOperation': any | null;
    'stockExchange'?: BusinessStockExchanges;
    'stockTicker'?: any | null;
    'messagingVolumeHigh': any | null;
    'address1': any | null;
    'address2'?: any | null;
    'city': any | null;
    'state': any | null;
    'postalCode': any | null;
    'country': any | null;
    'firstName': any | null;
    'lastName': any | null;
    'email': any | null;
    'jobTitle': any | null;
    'jobPosition': JobPosition;
    'phoneNumber': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isTwilioTermsRead",
            "baseName": "isTwilioTermsRead",
            "type": "any"
        },
        {
            "name": "isPrivacyPolicyOnWebsite",
            "baseName": "isPrivacyPolicyOnWebsite",
            "type": "any"
        },
        {
            "name": "isTosOnWebsite",
            "baseName": "isTosOnWebsite",
            "type": "any"
        },
        {
            "name": "isStopUnderstood",
            "baseName": "isStopUnderstood",
            "type": "any"
        },
        {
            "name": "isManualRead",
            "baseName": "isManualRead",
            "type": "any"
        },
        {
            "name": "isCtiaShortCodeRead",
            "baseName": "isCtiaShortCodeRead",
            "type": "any"
        },
        {
            "name": "isStandardsUnderstood",
            "baseName": "isStandardsUnderstood",
            "type": "any"
        },
        {
            "name": "isShortCodeUnderstood",
            "baseName": "isShortCodeUnderstood",
            "type": "any"
        },
        {
            "name": "isOptInOutUnderstood",
            "baseName": "isOptInOutUnderstood",
            "type": "any"
        },
        {
            "name": "isShortCodeTransferUnderstood",
            "baseName": "isShortCodeTransferUnderstood",
            "type": "any"
        },
        {
            "name": "isPricingUnderstood",
            "baseName": "isPricingUnderstood",
            "type": "any"
        },
        {
            "name": "isShortCodeTimelineUnderstood",
            "baseName": "isShortCodeTimelineUnderstood",
            "type": "any"
        },
        {
            "name": "businessName",
            "baseName": "businessName",
            "type": "any"
        },
        {
            "name": "businessType",
            "baseName": "businessType",
            "type": "BusinessType"
        },
        {
            "name": "businessClassification",
            "baseName": "businessClassification",
            "type": "BusinessClassification"
        },
        {
            "name": "businessIndustry",
            "baseName": "businessIndustry",
            "type": "BusinessIndustry"
        },
        {
            "name": "taxIDType",
            "baseName": "taxIDType",
            "type": "BusinessRegistrationIdentifier"
        },
        {
            "name": "taxID",
            "baseName": "taxID",
            "type": "any"
        },
        {
            "name": "websiteURL",
            "baseName": "websiteURL",
            "type": "any"
        },
        {
            "name": "socialMediaURL",
            "baseName": "socialMediaURL",
            "type": "any"
        },
        {
            "name": "regionsOfOperation",
            "baseName": "regionsOfOperation",
            "type": "any"
        },
        {
            "name": "stockExchange",
            "baseName": "stockExchange",
            "type": "BusinessStockExchanges"
        },
        {
            "name": "stockTicker",
            "baseName": "stockTicker",
            "type": "any"
        },
        {
            "name": "messagingVolumeHigh",
            "baseName": "messagingVolumeHigh",
            "type": "any"
        },
        {
            "name": "address1",
            "baseName": "address1",
            "type": "any"
        },
        {
            "name": "address2",
            "baseName": "address2",
            "type": "any"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "any"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "any"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "any"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "any"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "any"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "any"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any"
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "any"
        },
        {
            "name": "jobPosition",
            "baseName": "jobPosition",
            "type": "JobPosition"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(A2PApplicationSubmission.attributeTypeMap);
    }
}

export namespace A2PApplicationSubmission {
}
