/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.35.0**, built 2026-08-17T18:06:46.120Z
 *
 * The version of the OpenAPI document: 2.35.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BusinessRegionsOfOperation {
    Africa = <any> 'AFRICA',
    Asia = <any> 'ASIA',
    Europe = <any> 'EUROPE',
    LatinAmerica = <any> 'LATIN_AMERICA',
    UsaAndCanada = <any> 'USA_AND_CANADA',
    Australia = <any> 'AUSTRALIA'
}
