/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T17:18:29.852Z
 *
 * The version of the OpenAPI document: 2.1.604
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BusinessRegistrationIdentifier {
    Ein = <any> 'EIN',
    Duns = <any> 'DUNS',
    Cbn = <any> 'CBN',
    Cn = <any> 'CN',
    Acn = <any> 'ACN',
    Cin = <any> 'CIN',
    Vat = <any> 'VAT',
    Vatrn = <any> 'VATRN',
    Rn = <any> 'RN',
    Other = <any> 'Other'
}
