/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.20.2**, built 2026-07-28T00:19:47.898Z
 *
 * The version of the OpenAPI document: 2.20.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BusinessClassificationNonProfit {
    NonProfit = <any> 'non-profit'
}
