/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.1.535
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BusinessClassification {
    Public = <any> 'public',
    Private = <any> 'private',
    NonProfit = <any> 'non-profit',
    Government = <any> 'government'
}
