/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.7.5**, built 2026-07-14T20:20:55.390Z
 *
 * The version of the OpenAPI document: 2.7.5
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum BusinessRegionsOfOperation {
    Africa = <any> 'AFRICA',
    Asia = <any> 'ASIA',
    Europe = <any> 'EUROPE',
    LatinAmerica = <any> 'LATIN_AMERICA',
    UsaAndCanada = <any> 'USA_AND_CANADA',
    Australia = <any> 'AUSTRALIA'
}
