/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.7.8**, built 2026-07-14T23:04:51.346Z
 *
 * The version of the OpenAPI document: 2.7.8
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChatCompletionAudio } from './chatCompletionAudio';

/**
* If the audio output modality is requested, this object contains data about the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).
*/
export class ChatCompletionMessageAudio {
    /**
    * Unique identifier for this audio response.
    */
    'id': any | null;
    /**
    * Base64 encoded audio bytes generated by the model, in the format specified in the request.
    */
    'data': any | null;
    /**
    * The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations.
    */
    'expiresAt': any | null;
    /**
    * Transcript of the audio generated by the model.
    */
    'transcript': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "any"
        },
        {
            "name": "transcript",
            "baseName": "transcript",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return ChatCompletionMessageAudio.attributeTypeMap;
    }
}

