/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.14.1**, built 2026-07-23T15:42:25.922Z
 *
 * The version of the OpenAPI document: 2.14.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CountClaimedComps200Response {
    'seats': number;
    'count': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "seats",
            "baseName": "seats",
            "type": "number"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CountClaimedComps200Response.attributeTypeMap;
    }
}

