/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.36.0**, built 2026-08-19T22:01:55.154Z
 *
 * The version of the OpenAPI document: 2.36.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EmployeeScheduleStartHour {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return EmployeeScheduleStartHour.attributeTypeMap;
    }
}

