/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.45.0**, built 2026-09-02T14:40:32.528Z
 *
 * The version of the OpenAPI document: 2.45.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FetchMembersCount200Response {
    'count': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return FetchMembersCount200Response.attributeTypeMap;
    }
}

