/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-05T07:29:54.586Z
 *
 * The version of the OpenAPI document: 2.1.604
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ImportedListRecipient } from './importedListRecipient';

export class FetchImportedListRecipientsByPage200Response {
    'total': number;
    'length': number;
    'results': Array<ImportedListRecipient>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ImportedListRecipient>"
        }    ];

    static getAttributeTypeMap() {
        return FetchImportedListRecipientsByPage200Response.attributeTypeMap;
    }
}

