/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.1.519
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicableTerminals } from './applicableTerminals';

export class LedgerEntry {
    'registerID': string;
    'registerType': ApplicableTerminals;
    'transactionID': string;
    'transactionType': string | null;
    'checkAmount': number;
    'transactionAmount': number;
    'checkBalance': number;
    'discountReceived': string;
    'paymentObjectPrefix': string;
    'paymentObjectID': string;
    'parentObjectPrefix': string;
    'parentObjectID': string | null;
    'metaValue': string;
    'id': string | null;
    'merchantID': string;
    'createdAt': Date;
    'updatedAt': Date;
    'isActive': boolean;
    'refundedLedgerEntryID'?: string;
    'transactionAmountDecimal': string;
    'transactionAmountString': string;
    'checkAmountDecimal': string;
    'checkAmountString': string;
    'checkBalanceDecimal': string;
    'checkBalanceString': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "registerID",
            "baseName": "registerID",
            "type": "string"
        },
        {
            "name": "registerType",
            "baseName": "registerType",
            "type": "ApplicableTerminals"
        },
        {
            "name": "transactionID",
            "baseName": "transactionID",
            "type": "string"
        },
        {
            "name": "transactionType",
            "baseName": "transactionType",
            "type": "string"
        },
        {
            "name": "checkAmount",
            "baseName": "checkAmount",
            "type": "number"
        },
        {
            "name": "transactionAmount",
            "baseName": "transactionAmount",
            "type": "number"
        },
        {
            "name": "checkBalance",
            "baseName": "checkBalance",
            "type": "number"
        },
        {
            "name": "discountReceived",
            "baseName": "discountReceived",
            "type": "string"
        },
        {
            "name": "paymentObjectPrefix",
            "baseName": "paymentObjectPrefix",
            "type": "string"
        },
        {
            "name": "paymentObjectID",
            "baseName": "paymentObjectID",
            "type": "string"
        },
        {
            "name": "parentObjectPrefix",
            "baseName": "parentObjectPrefix",
            "type": "string"
        },
        {
            "name": "parentObjectID",
            "baseName": "parentObjectID",
            "type": "string"
        },
        {
            "name": "metaValue",
            "baseName": "metaValue",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "refundedLedgerEntryID",
            "baseName": "refundedLedgerEntryID",
            "type": "string"
        },
        {
            "name": "transactionAmountDecimal",
            "baseName": "transactionAmount_decimal",
            "type": "string"
        },
        {
            "name": "transactionAmountString",
            "baseName": "transactionAmount_string",
            "type": "string"
        },
        {
            "name": "checkAmountDecimal",
            "baseName": "checkAmount_decimal",
            "type": "string"
        },
        {
            "name": "checkAmountString",
            "baseName": "checkAmount_string",
            "type": "string"
        },
        {
            "name": "checkBalanceDecimal",
            "baseName": "checkBalance_decimal",
            "type": "string"
        },
        {
            "name": "checkBalanceString",
            "baseName": "checkBalance_string",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LedgerEntry.attributeTypeMap;
    }
}

