/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T09:49:03.606Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WTBillingVerifyPaymentMethodResponseBillingCadence } from './wTBillingVerifyPaymentMethodResponseBillingCadence';

export class Merchant extends null<String, any> {
    'companyName': any | null;
    'address1': any | null;
    'address2': any | null;
    'city': any | null;
    'state': any | null;
    'country': any | null;
    'phoneNumber': any | null;
    'zip': any | null;
    'currencyAbbreviation'?: any | null;
    'id': string;
    'createdAt': any | null;
    'updatedAt': any | null;
    'industry': any | null;
    'industryName': any | null;
    'infoGenesisPropertyID': any | null;
    'isFrozen': any | null;
    'billingContactEmployeeID': any | null;
    'marketingContactEmployeeID': any | null;
    'technicalContactEmployeeID': any | null;
    'customerServiceContactEmployeeID': any | null;
    'stripeCustomerID': any | null;
    'stripeConnectAccountID'?: any | null;
    'stripeConnectChargesEnabled'?: any | null;
    'stripeConnectPayoutsEnabled'?: any | null;
    'stripeConnectDetailsSubmitted'?: any | null;
    'stripeConnectOnboardingStatus'?: any | null;
    'isPaymentMethodProvided': any | null;
    'planNickname': any | null;
    'billingCadence'?: WTBillingVerifyPaymentMethodResponseBillingCadence;
    'maxSMSCount': any | null;
    'isSmsAgreement'?: any | null;
    'isWhiteLabeled'?: any | null;
    'isFeatured'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "any"
        },
        {
            "name": "address1",
            "baseName": "address1",
            "type": "any"
        },
        {
            "name": "address2",
            "baseName": "address2",
            "type": "any"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "any"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "any"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "any"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "any"
        },
        {
            "name": "zip",
            "baseName": "zip",
            "type": "any"
        },
        {
            "name": "currencyAbbreviation",
            "baseName": "currencyAbbreviation",
            "type": "any"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "any"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "any"
        },
        {
            "name": "industry",
            "baseName": "industry",
            "type": "any"
        },
        {
            "name": "industryName",
            "baseName": "industryName",
            "type": "any"
        },
        {
            "name": "infoGenesisPropertyID",
            "baseName": "infoGenesisPropertyID",
            "type": "any"
        },
        {
            "name": "isFrozen",
            "baseName": "isFrozen",
            "type": "any"
        },
        {
            "name": "billingContactEmployeeID",
            "baseName": "billingContactEmployeeID",
            "type": "any"
        },
        {
            "name": "marketingContactEmployeeID",
            "baseName": "marketingContactEmployeeID",
            "type": "any"
        },
        {
            "name": "technicalContactEmployeeID",
            "baseName": "technicalContactEmployeeID",
            "type": "any"
        },
        {
            "name": "customerServiceContactEmployeeID",
            "baseName": "customerServiceContactEmployeeID",
            "type": "any"
        },
        {
            "name": "stripeCustomerID",
            "baseName": "stripeCustomerID",
            "type": "any"
        },
        {
            "name": "stripeConnectAccountID",
            "baseName": "stripeConnectAccountID",
            "type": "any"
        },
        {
            "name": "stripeConnectChargesEnabled",
            "baseName": "stripeConnectChargesEnabled",
            "type": "any"
        },
        {
            "name": "stripeConnectPayoutsEnabled",
            "baseName": "stripeConnectPayoutsEnabled",
            "type": "any"
        },
        {
            "name": "stripeConnectDetailsSubmitted",
            "baseName": "stripeConnectDetailsSubmitted",
            "type": "any"
        },
        {
            "name": "stripeConnectOnboardingStatus",
            "baseName": "stripeConnectOnboardingStatus",
            "type": "any"
        },
        {
            "name": "isPaymentMethodProvided",
            "baseName": "isPaymentMethodProvided",
            "type": "any"
        },
        {
            "name": "planNickname",
            "baseName": "planNickname",
            "type": "any"
        },
        {
            "name": "billingCadence",
            "baseName": "billingCadence",
            "type": "WTBillingVerifyPaymentMethodResponseBillingCadence"
        },
        {
            "name": "maxSMSCount",
            "baseName": "maxSMSCount",
            "type": "any"
        },
        {
            "name": "isSmsAgreement",
            "baseName": "isSmsAgreement",
            "type": "any"
        },
        {
            "name": "isWhiteLabeled",
            "baseName": "isWhiteLabeled",
            "type": "any"
        },
        {
            "name": "isFeatured",
            "baseName": "isFeatured",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Merchant.attributeTypeMap);
    }
}

