/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.1.527
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MSAnalyticsMemberPointsRedeemedPartitionedByDate {
    /**
    * Represents the date of points redemption
    */
    'date': string;
    /**
    * Represents the sum of points redeemed on that particular date
    */
    'points': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MSAnalyticsMemberPointsRedeemedPartitionedByDate.attributeTypeMap;
    }
}

