/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.8.2**, built 2026-07-15T19:49:51.896Z
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MSAnalyticsMembershipTierAmountRefundedPartitionedByDate extends null<String, any> {
    /**
    * Represents the date when the amount was refunded
    */
    'date': any | null;
    /**
    * Represents the amount refunded on that particular date
    */
    'amount': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "any"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MSAnalyticsMembershipTierAmountRefundedPartitionedByDate.attributeTypeMap);
    }
}

