/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-15T19:47:21.833Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MSMerchantCreditHistory extends null<String, any> {
    /**
    * Optional Member ID as represented by the merchant
    */
    'memberIdentifier'?: any | null;
    'mobileNumber': any | null;
    /**
    * The amount that needs to be credited to the member
    */
    'creditAmount': any | null;
    /**
    * The UUID of this record
    */
    'id': any | null;
    'merchantCreditID': string;
    'merchantID': string;
    /**
    * The timestamp of when this resource was created
    */
    'createdAt': any | null;
    /**
    * Denotes if this resource is active
    */
    'isActive': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "memberIdentifier",
            "baseName": "memberIdentifier",
            "type": "any"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "any"
        },
        {
            "name": "creditAmount",
            "baseName": "creditAmount",
            "type": "any"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "any"
        },
        {
            "name": "merchantCreditID",
            "baseName": "merchantCreditID",
            "type": "string"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "any"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MSMerchantCreditHistory.attributeTypeMap);
    }
}

