/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T03:32:46.578Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AmenityId } from './amenityId';

export class Performance extends null<String, any> {
    'title': any | null;
    'body': any | null;
    'startDateTime': any | null;
    'price': any | null;
    'url': any | null;
    'orderNumber': any | null;
    /**
    * Denotes if the event has been sold out
    */
    'isSoldOut': any | null;
    'mediaURL'?: any | null;
    'paymentDesignID'?: string;
    'maxCompTickets'?: any | null;
    'ticketExpirationDateTime'?: any | null;
    'redemptionInstructions'?: any | null;
    'id': AmenityId;
    'createdAt': any | null;
    'updatedAt': any | null;
    'isActive': any | null;
    'merchantID': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "any"
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "any"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "any"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "any"
        },
        {
            "name": "orderNumber",
            "baseName": "orderNumber",
            "type": "any"
        },
        {
            "name": "isSoldOut",
            "baseName": "isSoldOut",
            "type": "any"
        },
        {
            "name": "mediaURL",
            "baseName": "mediaURL",
            "type": "any"
        },
        {
            "name": "paymentDesignID",
            "baseName": "paymentDesignID",
            "type": "string"
        },
        {
            "name": "maxCompTickets",
            "baseName": "maxCompTickets",
            "type": "any"
        },
        {
            "name": "ticketExpirationDateTime",
            "baseName": "ticketExpirationDateTime",
            "type": "any"
        },
        {
            "name": "redemptionInstructions",
            "baseName": "redemptionInstructions",
            "type": "any"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "AmenityId"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "any"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "any"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "any"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Performance.attributeTypeMap);
    }
}

