/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.20.2**, built 2026-07-30T15:35:41.764Z
 *
 * The version of the OpenAPI document: 2.20.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BusinessType } from './businessType';

/**
* From T, pick a set of properties whose keys are in the union K
*/
export class PickA2PBaseIntakeExcludeKeyofA2PBaseIntakeBusinessClassificationOrBusinessIndustryOrTaxIDTypeOrTaxIDOrWebsiteURLOrSocialMediaURLOrRegionsOfOperationOrMessagingVolumeHighOrJobTitleOrJobPosition {
    'firstName': string;
    'lastName': string;
    'email': string;
    'businessName': string;
    'businessType': BusinessType;
    'address1': string;
    'address2'?: string;
    'city': string;
    'state': string;
    'postalCode': string;
    'country': string;
    'phoneNumber': string;
    'isTwilioTermsRead': boolean;
    'isWalletSmsTermsRead': boolean;
    'isPricingUnderstood': boolean;
    'isPrivacyAndTosPresent': boolean;
    'privacyPolicyUrl'?: string;
    'willObtainConsent': boolean;
    'willHonorOptOut': boolean;
    'willFollowContentRules': boolean;
    'willComplyLawAndHours': boolean;
    'infoIsAccurate': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "businessName",
            "baseName": "businessName",
            "type": "string"
        },
        {
            "name": "businessType",
            "baseName": "businessType",
            "type": "BusinessType"
        },
        {
            "name": "address1",
            "baseName": "address1",
            "type": "string"
        },
        {
            "name": "address2",
            "baseName": "address2",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "isTwilioTermsRead",
            "baseName": "isTwilioTermsRead",
            "type": "boolean"
        },
        {
            "name": "isWalletSmsTermsRead",
            "baseName": "isWalletSmsTermsRead",
            "type": "boolean"
        },
        {
            "name": "isPricingUnderstood",
            "baseName": "isPricingUnderstood",
            "type": "boolean"
        },
        {
            "name": "isPrivacyAndTosPresent",
            "baseName": "isPrivacyAndTosPresent",
            "type": "boolean"
        },
        {
            "name": "privacyPolicyUrl",
            "baseName": "privacyPolicyUrl",
            "type": "string"
        },
        {
            "name": "willObtainConsent",
            "baseName": "willObtainConsent",
            "type": "boolean"
        },
        {
            "name": "willHonorOptOut",
            "baseName": "willHonorOptOut",
            "type": "boolean"
        },
        {
            "name": "willFollowContentRules",
            "baseName": "willFollowContentRules",
            "type": "boolean"
        },
        {
            "name": "willComplyLawAndHours",
            "baseName": "willComplyLawAndHours",
            "type": "boolean"
        },
        {
            "name": "infoIsAccurate",
            "baseName": "infoIsAccurate",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PickA2PBaseIntakeExcludeKeyofA2PBaseIntakeBusinessClassificationOrBusinessIndustryOrTaxIDTypeOrTaxIDOrWebsiteURLOrSocialMediaURLOrRegionsOfOperationOrMessagingVolumeHighOrJobTitleOrJobPosition.attributeTypeMap;
    }
}

export namespace PickA2PBaseIntakeExcludeKeyofA2PBaseIntakeBusinessClassificationOrBusinessIndustryOrTaxIDTypeOrTaxIDOrWebsiteURLOrSocialMediaURLOrRegionsOfOperationOrMessagingVolumeHighOrJobTitleOrJobPosition {
}
