/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.8.2**, built 2026-07-15T19:49:51.896Z
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Plan extends null<String, any> {
    'name': string;
    'price': string;
    'features': any | null;
    'measurement'?: string;
    'isExceeded'?: boolean;
    'isCurrent'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "any"
        },
        {
            "name": "measurement",
            "baseName": "measurement",
            "type": "string"
        },
        {
            "name": "isExceeded",
            "baseName": "isExceeded",
            "type": "boolean"
        },
        {
            "name": "isCurrent",
            "baseName": "isCurrent",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Plan.attributeTypeMap);
    }
}

