/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.7.5**, built 2026-07-14T20:20:55.390Z
 *
 * The version of the OpenAPI document: 2.7.5
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Status {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return Status.attributeTypeMap;
    }
}

