/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 3.0.0**, built 2026-09-11T22:37:06.945Z
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum TrustBundleStatuses {
    Draft = <any> 'draft',
    PendingReview = <any> 'pending-review',
    InReview = <any> 'in-review',
    TwilioRejected = <any> 'twilio-rejected',
    TwilioApproved = <any> 'twilio-approved'
}
