/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-15T13:30:53.626Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AmenityId } from './amenityId';
import { VideoProvider } from './videoProvider';
import { WTVideoPlaybackSource } from './wTVideoPlaybackSource';

export class Video extends null<String, any> {
    'id': AmenityId;
    'createdAt': any | null;
    'updatedAt': any | null;
    'title': any | null;
    'description': any | null;
    'orderNumber': any | null;
    'additionalInfoURL'?: any | null;
    'isActive': any | null;
    'merchantID': string;
    'provider': VideoProvider;
    'assetId': any | null;
    'source': WTVideoPlaybackSource;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "AmenityId"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "any"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "any"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "any"
        },
        {
            "name": "orderNumber",
            "baseName": "orderNumber",
            "type": "any"
        },
        {
            "name": "additionalInfoURL",
            "baseName": "additionalInfoURL",
            "type": "any"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "any"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "VideoProvider"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "any"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "WTVideoPlaybackSource"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Video.attributeTypeMap);
    }
}

