/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T22:20:36.187Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class VSCampaignGeneratedMessage extends null<String, any> {
    'staticVoucherID': string;
    'message': any | null;
    'cellPhoneNumber': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "staticVoucherID",
            "baseName": "staticVoucherID",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "any"
        },
        {
            "name": "cellPhoneNumber",
            "baseName": "cellPhoneNumber",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VSCampaignGeneratedMessage.attributeTypeMap);
    }
}

