/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-24T12:17:36.814Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTAndroidKeystoreResponse extends null<String, any> {
    'keystoreBase64': any | null;
    'fingerprint': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keystoreBase64",
            "baseName": "keystoreBase64",
            "type": "any"
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTAndroidKeystoreResponse.attributeTypeMap);
    }
}

