/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.50.0**, built 2026-09-30T15:17:15.284Z
 *
 * The version of the OpenAPI document: 2.50.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTApplePassStyle extends null<String, any> {
    'backgroundColor'?: any | null;
    'foregroundColor'?: any | null;
    'labelColor'?: any | null;
    'stripColor'?: any | null;
    'logoUrl'?: any | null;
    'iconUrl'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "backgroundColor",
            "baseName": "backgroundColor",
            "type": "any"
        },
        {
            "name": "foregroundColor",
            "baseName": "foregroundColor",
            "type": "any"
        },
        {
            "name": "labelColor",
            "baseName": "labelColor",
            "type": "any"
        },
        {
            "name": "stripColor",
            "baseName": "stripColor",
            "type": "any"
        },
        {
            "name": "logoUrl",
            "baseName": "logoUrl",
            "type": "any"
        },
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTApplePassStyle.attributeTypeMap);
    }
}

