/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.14.0**, built 2026-07-23T13:47:46.641Z
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTAuthenticationLoginRequest extends null<String, any> {
    'username': any | null;
    'password': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "any"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTAuthenticationLoginRequest.attributeTypeMap);
    }
}

