/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.7.9**, built 2026-07-15T00:03:41.695Z
 *
 * The version of the OpenAPI document: 2.7.9
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTAuthenticationCheckSessionTokenStatusResponse extends null<String, any> {
    'status': WTAuthenticationCheckSessionTokenStatusResponse.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "WTAuthenticationCheckSessionTokenStatusResponse.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTAuthenticationCheckSessionTokenStatusResponse.attributeTypeMap);
    }
}

export namespace WTAuthenticationCheckSessionTokenStatusResponse {
    export enum StatusEnum {
        Valid = <any> 'Valid'
    }
}
