/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T17:18:29.852Z
 *
 * The version of the OpenAPI document: 2.1.604
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTBillingSavePaymentMethod extends null<String, any> {
    'paymentMethodID': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentMethodID",
            "baseName": "paymentMethodID",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTBillingSavePaymentMethod.attributeTypeMap);
    }
}

