/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.7.0**, built 2026-07-13T17:37:09.944Z
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTConnectRequirements extends null<String, any> {
    'currentlyDue': any | null;
    'pastDue': any | null;
    'eventuallyDue': any | null;
    'pendingVerification': any | null;
    'disabledReason'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentlyDue",
            "baseName": "currentlyDue",
            "type": "any"
        },
        {
            "name": "pastDue",
            "baseName": "pastDue",
            "type": "any"
        },
        {
            "name": "eventuallyDue",
            "baseName": "eventuallyDue",
            "type": "any"
        },
        {
            "name": "pendingVerification",
            "baseName": "pendingVerification",
            "type": "any"
        },
        {
            "name": "disabledReason",
            "baseName": "disabledReason",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTConnectRequirements.attributeTypeMap);
    }
}

