/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T22:41:01.331Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTCountResult extends null<String, any> {
    'count': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTCountResult.attributeTypeMap);
    }
}

