/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.13.0**, built 2026-07-21T16:58:00.801Z
 *
 * The version of the OpenAPI document: 2.13.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WTConnectOnboardingStatus } from './wTConnectOnboardingStatus';
import { WTConnectRequirements } from './wTConnectRequirements';

export class WTConnectAccountStatus extends null<String, any> {
    'accountId': any | null;
    'onboardingStatus': WTConnectOnboardingStatus;
    'detailsSubmitted': any | null;
    'chargesEnabled': any | null;
    'payoutsEnabled': any | null;
    'ecommerceEligible': any | null;
    'requirements': WTConnectRequirements;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "any"
        },
        {
            "name": "onboardingStatus",
            "baseName": "onboardingStatus",
            "type": "WTConnectOnboardingStatus"
        },
        {
            "name": "detailsSubmitted",
            "baseName": "detailsSubmitted",
            "type": "any"
        },
        {
            "name": "chargesEnabled",
            "baseName": "chargesEnabled",
            "type": "any"
        },
        {
            "name": "payoutsEnabled",
            "baseName": "payoutsEnabled",
            "type": "any"
        },
        {
            "name": "ecommerceEligible",
            "baseName": "ecommerceEligible",
            "type": "any"
        },
        {
            "name": "requirements",
            "baseName": "requirements",
            "type": "WTConnectRequirements"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTConnectAccountStatus.attributeTypeMap);
    }
}

