/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.47.4**, built 2026-09-15T21:54:49.314Z
 *
 * The version of the OpenAPI document: 2.47.4
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTConnectOnboardingLinkRequest extends null<String, any> {
    'returnUrl': any | null;
    'refreshUrl': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "returnUrl",
            "baseName": "returnUrl",
            "type": "any"
        },
        {
            "name": "refreshUrl",
            "baseName": "refreshUrl",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTConnectOnboardingLinkRequest.attributeTypeMap);
    }
}

