/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.5.0**, built 2026-07-12T09:49:39.468Z
 *
 * The version of the OpenAPI document: 2.5.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTEmployeePeerRoles extends null<String, any> {
    'rolesArray'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rolesArray",
            "baseName": "rolesArray",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTEmployeePeerRoles.attributeTypeMap);
    }
}

