/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-23T14:08:22.742Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTEmployeeScheduleSMSCampaignBroadcast extends null<String, any> {
    'phoneNumberID': string;
    'messageTemplate': any | null;
    'sendQRCode': any | null;
    'mediaURLs'?: any | null;
    'broadcastScheduledAt': any | null;
    'locale': any | null;
    'timezone': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "phoneNumberID",
            "baseName": "phoneNumberID",
            "type": "string"
        },
        {
            "name": "messageTemplate",
            "baseName": "messageTemplate",
            "type": "any"
        },
        {
            "name": "sendQRCode",
            "baseName": "sendQRCode",
            "type": "any"
        },
        {
            "name": "mediaURLs",
            "baseName": "mediaURLs",
            "type": "any"
        },
        {
            "name": "broadcastScheduledAt",
            "baseName": "broadcastScheduledAt",
            "type": "any"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "any"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTEmployeeScheduleSMSCampaignBroadcast.attributeTypeMap);
    }
}

