/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T15:48:48.361Z
 *
 * The version of the OpenAPI document: 2.1.604
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTEmployeeUpdateRecords extends null<String, any> {
    'fileName': any | null;
    'bucket': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "any"
        },
        {
            "name": "bucket",
            "baseName": "bucket",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTEmployeeUpdateRecords.attributeTypeMap);
    }
}

