/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.45.0**, built 2026-09-02T14:40:32.528Z
 *
 * The version of the OpenAPI document: 2.45.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WTGuestAmountBreakdown } from './wTGuestAmountBreakdown';

export class WTGuestCreatePaymentIntentResponse extends null<String, any> {
    'orderID': any | null;
    'reservationID': any | null;
    'chargeModel': WTGuestCreatePaymentIntentResponse.ChargeModelEnum;
    'currency': any | null;
    'clientSecret': any | null;
    'paymentIntentID': any | null;
    'connectedAccountId': any | null;
    'publishableKey': any | null;
    'amountBreakdown': WTGuestAmountBreakdown;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderID",
            "baseName": "orderID",
            "type": "any"
        },
        {
            "name": "reservationID",
            "baseName": "reservationID",
            "type": "any"
        },
        {
            "name": "chargeModel",
            "baseName": "chargeModel",
            "type": "WTGuestCreatePaymentIntentResponse.ChargeModelEnum"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "any"
        },
        {
            "name": "clientSecret",
            "baseName": "clientSecret",
            "type": "any"
        },
        {
            "name": "paymentIntentID",
            "baseName": "paymentIntentID",
            "type": "any"
        },
        {
            "name": "connectedAccountId",
            "baseName": "connectedAccountId",
            "type": "any"
        },
        {
            "name": "publishableKey",
            "baseName": "publishableKey",
            "type": "any"
        },
        {
            "name": "amountBreakdown",
            "baseName": "amountBreakdown",
            "type": "WTGuestAmountBreakdown"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTGuestCreatePaymentIntentResponse.attributeTypeMap);
    }
}

export namespace WTGuestCreatePaymentIntentResponse {
    export enum ChargeModelEnum {
        Direct = <any> 'direct'
    }
}
