/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.44.0**, built 2026-09-01T14:02:40.244Z
 *
 * The version of the OpenAPI document: 2.44.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTInfoGenesisUniquePostingIDs extends null<String, any> {
    'uniquePostingIDs': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniquePostingIDs",
            "baseName": "uniquePostingIDs",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTInfoGenesisUniquePostingIDs.attributeTypeMap);
    }
}

