/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.3.2**, built 2026-07-08T19:09:48.480Z
 *
 * The version of the OpenAPI document: 2.3.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTInfoGenesisRecordFilterParameters extends null<String, any> {
    'startDateTime': any | null;
    'endDateTime': any | null;
    'selectedRegisters'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "any"
        },
        {
            "name": "endDateTime",
            "baseName": "endDateTime",
            "type": "any"
        },
        {
            "name": "selectedRegisters",
            "baseName": "selectedRegisters",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTInfoGenesisRecordFilterParameters.attributeTypeMap);
    }
}

