/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.1.535
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MessageDirection } from './messageDirection';
import { MessageStatus } from './messageStatus';

/**
* tsoaModel
*/
export class WTMessageInstance {
    /**
    * Construct a type with a set of properties K of type T
    */
    'subresourceUris': object;
    'apiVersion': string;
    'priceUnit': string;
    'errorCode': number;
    'dateCreated': Date;
    'dateSent': Date;
    'sid': string;
    'messagingServiceSid': string;
    'status': MessageStatus;
    'numMedia': string;
    'accountSid': string;
    'uri': string;
    'errorMessage': string;
    'price': string;
    'dateUpdated': Date;
    'to': string;
    'from': string;
    'direction': MessageDirection;
    'numSegments': string;
    'body': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subresourceUris",
            "baseName": "subresourceUris",
            "type": "object"
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        },
        {
            "name": "priceUnit",
            "baseName": "priceUnit",
            "type": "string"
        },
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "number"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date"
        },
        {
            "name": "dateSent",
            "baseName": "dateSent",
            "type": "Date"
        },
        {
            "name": "sid",
            "baseName": "sid",
            "type": "string"
        },
        {
            "name": "messagingServiceSid",
            "baseName": "messagingServiceSid",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MessageStatus"
        },
        {
            "name": "numMedia",
            "baseName": "numMedia",
            "type": "string"
        },
        {
            "name": "accountSid",
            "baseName": "accountSid",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "Date"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "MessageDirection"
        },
        {
            "name": "numSegments",
            "baseName": "numSegments",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WTMessageInstance.attributeTypeMap;
    }
}

