/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.50.0**, built 2026-09-29T14:31:11.531Z
 *
 * The version of the OpenAPI document: 2.50.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTMerchantCreditCreationParams extends null<String, any> {
    'mobileNumber': any | null;
    /**
    * The amount that needs to be credited to the member
    */
    'creditAmount': any | null;
    /**
    * MerchantCredit ID as represented by the merchant
    */
    'memberID'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "any"
        },
        {
            "name": "creditAmount",
            "baseName": "creditAmount",
            "type": "any"
        },
        {
            "name": "memberID",
            "baseName": "memberID",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTMerchantCreditCreationParams.attributeTypeMap);
    }
}

