/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.3.2**, built 2026-07-08T19:12:45.634Z
 *
 * The version of the OpenAPI document: 2.3.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The id of the membership tier - autopopulated by the service
*/
export class WTMembershipTierId {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return WTMembershipTierId.attributeTypeMap;
    }
}

