/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-16T12:02:06.305Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTMerchantUpdatePOSIntegration extends null<String, any> {
    'infoGenesisPropertyID': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "infoGenesisPropertyID",
            "baseName": "infoGenesisPropertyID",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTMerchantUpdatePOSIntegration.attributeTypeMap);
    }
}

