/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTPerformanceCreateParams extends null<String, any> {
    'title': any | null;
    'body': any | null;
    'startDateTime': Date;
    'price': any | null;
    'url': any | null;
    'orderNumber': any | null;
    /**
    * Denotes if the event has been sold out
    */
    'isSoldOut': any | null;
    'mediaURL'?: string;
    'paymentDesignID'?: string;
    'maxCompTickets'?: number;
    'ticketExpirationDateTime'?: Date;
    'redemptionInstructions'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "any"
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "any"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "any"
        },
        {
            "name": "orderNumber",
            "baseName": "orderNumber",
            "type": "any"
        },
        {
            "name": "isSoldOut",
            "baseName": "isSoldOut",
            "type": "any"
        },
        {
            "name": "mediaURL",
            "baseName": "mediaURL",
            "type": "string"
        },
        {
            "name": "paymentDesignID",
            "baseName": "paymentDesignID",
            "type": "string"
        },
        {
            "name": "maxCompTickets",
            "baseName": "maxCompTickets",
            "type": "number"
        },
        {
            "name": "ticketExpirationDateTime",
            "baseName": "ticketExpirationDateTime",
            "type": "Date"
        },
        {
            "name": "redemptionInstructions",
            "baseName": "redemptionInstructions",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTPerformanceCreateParams.attributeTypeMap);
    }
}

