/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 3.0.0**, built 2026-09-11T22:37:06.945Z
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTPrizeGamePlayResultPrize {
    'title'?: any | null;
    'scanID': any | null;
    'advertisementCreditID': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "scanID",
            "baseName": "scanID",
            "type": "any"
        },
        {
            "name": "advertisementCreditID",
            "baseName": "advertisementCreditID",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return WTPrizeGamePlayResultPrize.attributeTypeMap;
    }
}

