/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.20.2**, built 2026-07-30T23:23:58.408Z
 *
 * The version of the OpenAPI document: 2.20.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTPublicBranding extends null<String, any> {
    'companyName'?: string;
    'headerBackgroundColor'?: string;
    'mobileAppIconURL'?: string;
    'showWalletCredit'?: boolean;
    'loginLogoURL'?: string;
    'loginPanelImageURL'?: string;
    'loginHeadline'?: string;
    'loginSubcopy'?: string;
    'loginBackgroundColor'?: string;
    'loginBackgroundImageURL'?: string;
    'registerURL'?: string;
    'loginFooterLinks'?: any | null;
    'desktopFrameLogoURL'?: string;
    'desktopFrameBackgroundColor'?: string;
    'desktopFrameBackgroundImageURL'?: string;
    'desktopFrameByline'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "headerBackgroundColor",
            "baseName": "headerBackgroundColor",
            "type": "string"
        },
        {
            "name": "mobileAppIconURL",
            "baseName": "mobileAppIconURL",
            "type": "string"
        },
        {
            "name": "showWalletCredit",
            "baseName": "showWalletCredit",
            "type": "boolean"
        },
        {
            "name": "loginLogoURL",
            "baseName": "loginLogoURL",
            "type": "string"
        },
        {
            "name": "loginPanelImageURL",
            "baseName": "loginPanelImageURL",
            "type": "string"
        },
        {
            "name": "loginHeadline",
            "baseName": "loginHeadline",
            "type": "string"
        },
        {
            "name": "loginSubcopy",
            "baseName": "loginSubcopy",
            "type": "string"
        },
        {
            "name": "loginBackgroundColor",
            "baseName": "loginBackgroundColor",
            "type": "string"
        },
        {
            "name": "loginBackgroundImageURL",
            "baseName": "loginBackgroundImageURL",
            "type": "string"
        },
        {
            "name": "registerURL",
            "baseName": "registerURL",
            "type": "string"
        },
        {
            "name": "loginFooterLinks",
            "baseName": "loginFooterLinks",
            "type": "any"
        },
        {
            "name": "desktopFrameLogoURL",
            "baseName": "desktopFrameLogoURL",
            "type": "string"
        },
        {
            "name": "desktopFrameBackgroundColor",
            "baseName": "desktopFrameBackgroundColor",
            "type": "string"
        },
        {
            "name": "desktopFrameBackgroundImageURL",
            "baseName": "desktopFrameBackgroundImageURL",
            "type": "string"
        },
        {
            "name": "desktopFrameByline",
            "baseName": "desktopFrameByline",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTPublicBranding.attributeTypeMap);
    }
}

