/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T22:18:43.991Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WTQuickLinkLinkBookSectionID } from './wTQuickLinkLinkBookSectionID';

export class WTQuickLinkUpdateParams extends null<String, any> {
    'title': any | null;
    'url': string;
    'icon': any | null;
    'orderNumber': number;
    'linkBookSectionID'?: WTQuickLinkLinkBookSectionID;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "any"
        },
        {
            "name": "orderNumber",
            "baseName": "orderNumber",
            "type": "number"
        },
        {
            "name": "linkBookSectionID",
            "baseName": "linkBookSectionID",
            "type": "WTQuickLinkLinkBookSectionID"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTQuickLinkUpdateParams.attributeTypeMap);
    }
}

