/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.47.3**, built 2026-09-14T15:33:08.576Z
 *
 * The version of the OpenAPI document: 2.47.3
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTSendFreeze extends null<String, any> {
    'origin': any | null;
    'reason'?: any | null;
    'frozenBy'?: any | null;
    'createdAt'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "origin",
            "baseName": "origin",
            "type": "any"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "any"
        },
        {
            "name": "frozenBy",
            "baseName": "frozenBy",
            "type": "any"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTSendFreeze.attributeTypeMap);
    }
}

