/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.20.2**, built 2026-08-02T16:57:50.829Z
 *
 * The version of the OpenAPI document: 2.20.2
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTSmsSubscriberCreateParams extends null<String, any> {
    'mobileNumber': any | null;
    'optInSource'?: any | null;
    'disclosureVersion'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "any"
        },
        {
            "name": "optInSource",
            "baseName": "optInSource",
            "type": "any"
        },
        {
            "name": "disclosureVersion",
            "baseName": "disclosureVersion",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTSmsSubscriberCreateParams.attributeTypeMap);
    }
}

