/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T07:21:07.284Z
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WTTCPAOptListID } from './wTTCPAOptListID';
import { WTTCPAOptSourceID } from './wTTCPAOptSourceID';

export class WTTCPAOpt extends null<String, any> {
    'listID': WTTCPAOptListID;
    'sourceID': WTTCPAOptSourceID;
    'phoneNumber': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "listID",
            "baseName": "listID",
            "type": "WTTCPAOptListID"
        },
        {
            "name": "sourceID",
            "baseName": "sourceID",
            "type": "WTTCPAOptSourceID"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTTCPAOpt.attributeTypeMap);
    }
}

