/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.1.533
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTVirtualBusinessCardCreateParams {
    'firstName': string;
    'lastName': string;
    'emailAddress': string;
    'designation': string;
    'phoneNumber': string;
    'introduction'?: string;
    'instagram'?: string;
    'facebook'?: string;
    'youTube'?: string;
    'twitter'?: string;
    'linkedIn'?: string;
    'whatsApp'?: string;
    'avatarURL'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "designation",
            "baseName": "designation",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "introduction",
            "baseName": "introduction",
            "type": "string"
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string"
        },
        {
            "name": "facebook",
            "baseName": "facebook",
            "type": "string"
        },
        {
            "name": "youTube",
            "baseName": "youTube",
            "type": "string"
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string"
        },
        {
            "name": "linkedIn",
            "baseName": "linkedIn",
            "type": "string"
        },
        {
            "name": "whatsApp",
            "baseName": "whatsApp",
            "type": "string"
        },
        {
            "name": "avatarURL",
            "baseName": "avatarURL",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WTVirtualBusinessCardCreateParams.attributeTypeMap;
    }
}

