/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.13.0**, built 2026-07-21T16:58:00.801Z
 *
 * The version of the OpenAPI document: 2.13.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WTVideoUploadProvisionProvider } from './wTVideoUploadProvisionProvider';

export class WTVideoUploadProvision extends null<String, any> {
    'provider': WTVideoUploadProvisionProvider;
    'url': any | null;
    'assetId': any | null;
    'hdIncluded': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "WTVideoUploadProvisionProvider"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "any"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "any"
        },
        {
            "name": "hdIncluded",
            "baseName": "hdIncluded",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTVideoUploadProvision.attributeTypeMap);
    }
}

