/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T22:35:21.773Z
 *
 * The version of the OpenAPI document: 2.1.604
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTVideoUpdateParams extends null<String, any> {
    'title': any | null;
    'description': any | null;
    'orderNumber': any | null;
    'additionalInfoURL'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "any"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "any"
        },
        {
            "name": "orderNumber",
            "baseName": "orderNumber",
            "type": "any"
        },
        {
            "name": "additionalInfoURL",
            "baseName": "additionalInfoURL",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTVideoUpdateParams.attributeTypeMap);
    }
}

