/**
 * wallet-api
 * API
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTWalletObjectPrefixCounts extends null<String, any> {
    'walletObjectPrefix': any | null;
    'walletObjectName': any | null;
    'list': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "walletObjectPrefix",
            "baseName": "walletObjectPrefix",
            "type": "any"
        },
        {
            "name": "walletObjectName",
            "baseName": "walletObjectName",
            "type": "any"
        },
        {
            "name": "list",
            "baseName": "list",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTWalletObjectPrefixCounts.attributeTypeMap);
    }
}

