/**
 * wallet-api
 * Wallet Inc. API reference.  **Spec version 2.7.3**, built 2026-07-14T04:37:03.852Z
 *
 * The version of the OpenAPI document: 2.7.3
 * Contact: development@wallet.inc
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WTWhatsAppInboundWebhook extends null<String, any> {
    'smsMessageSid': string;
    'numMedia': any | null;
    'profileName': string;
    'smsSid': string;
    'waId': string;
    'smsStatus': string;
    'body': string;
    'to': string;
    'numSegments': any | null;
    'messageSid': string;
    'accountSid': string;
    'from': string;
    'apiVersion': string;
    'mediaUrls'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "smsMessageSid",
            "baseName": "SmsMessageSid",
            "type": "string"
        },
        {
            "name": "numMedia",
            "baseName": "NumMedia",
            "type": "any"
        },
        {
            "name": "profileName",
            "baseName": "ProfileName",
            "type": "string"
        },
        {
            "name": "smsSid",
            "baseName": "SmsSid",
            "type": "string"
        },
        {
            "name": "waId",
            "baseName": "WaId",
            "type": "string"
        },
        {
            "name": "smsStatus",
            "baseName": "SmsStatus",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "Body",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "To",
            "type": "string"
        },
        {
            "name": "numSegments",
            "baseName": "NumSegments",
            "type": "any"
        },
        {
            "name": "messageSid",
            "baseName": "MessageSid",
            "type": "string"
        },
        {
            "name": "accountSid",
            "baseName": "AccountSid",
            "type": "string"
        },
        {
            "name": "from",
            "baseName": "From",
            "type": "string"
        },
        {
            "name": "apiVersion",
            "baseName": "ApiVersion",
            "type": "string"
        },
        {
            "name": "mediaUrls",
            "baseName": "MediaUrls",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WTWhatsAppInboundWebhook.attributeTypeMap);
    }
}

