export * from './aPIKeysApi';
import { APIKeysApi } from './aPIKeysApi';
export * from './amenitiesApi';
import { AmenitiesApi } from './amenitiesApi';
export * from './analyticsApi';
import { AnalyticsApi } from './analyticsApi';
export * from './appToPersonA2PRegistrationApi';
import { AppToPersonA2PRegistrationApi } from './appToPersonA2PRegistrationApi';
export * from './appleWalletSubscribersApi';
import { AppleWalletSubscribersApi } from './appleWalletSubscribersApi';
export * from './authenticationApi';
import { AuthenticationApi } from './authenticationApi';
export * from './billingPaymentsApi';
import { BillingPaymentsApi } from './billingPaymentsApi';
export * from './clubMembersApi';
import { ClubMembersApi } from './clubMembersApi';
export * from './countriesApi';
import { CountriesApi } from './countriesApi';
export * from './customerApi';
import { CustomerApi } from './customerApi';
export * from './dashboardSummariesApi';
import { DashboardSummariesApi } from './dashboardSummariesApi';
export * from './diningApi';
import { DiningApi } from './diningApi';
export * from './dynamicVouchersApi';
import { DynamicVouchersApi } from './dynamicVouchersApi';
export * from './emailSubscribersApi';
import { EmailSubscribersApi } from './emailSubscribersApi';
export * from './employeesApi';
import { EmployeesApi } from './employeesApi';
export * from './galleryApi';
import { GalleryApi } from './galleryApi';
export * from './gamingApi';
import { GamingApi } from './gamingApi';
export * from './industriesApi';
import { IndustriesApi } from './industriesApi';
export * from './infoGenesisReportsApi';
import { InfoGenesisReportsApi } from './infoGenesisReportsApi';
export * from './interactionsApi';
import { InteractionsApi } from './interactionsApi';
export * from './loungeApi';
import { LoungeApi } from './loungeApi';
export * from './membershipTiersApi';
import { MembershipTiersApi } from './membershipTiersApi';
export * from './merchantApi';
import { MerchantApi } from './merchantApi';
export * from './merchantCreditsApi';
import { MerchantCreditsApi } from './merchantCreditsApi';
export * from './newsApi';
import { NewsApi } from './newsApi';
export * from './openAIApi';
import { OpenAIApi } from './openAIApi';
export * from './paymentDesignsApi';
import { PaymentDesignsApi } from './paymentDesignsApi';
export * from './performancesApi';
import { PerformancesApi } from './performancesApi';
export * from './pointOfSaleConfigurationApi';
import { PointOfSaleConfigurationApi } from './pointOfSaleConfigurationApi';
export * from './prizesApi';
import { PrizesApi } from './prizesApi';
export * from './productsApi';
import { ProductsApi } from './productsApi';
export * from './promotionCodesApi';
import { PromotionCodesApi } from './promotionCodesApi';
export * from './qRCodeDesignsApi';
import { QRCodeDesignsApi } from './qRCodeDesignsApi';
export * from './quickLinksApi';
import { QuickLinksApi } from './quickLinksApi';
export * from './quickLinksSectionApi';
import { QuickLinksSectionApi } from './quickLinksSectionApi';
export * from './roomRatesApi';
import { RoomRatesApi } from './roomRatesApi';
export * from './sMSOperationsApi';
import { SMSOperationsApi } from './sMSOperationsApi';
export * from './sMSSubscribersApi';
import { SMSSubscribersApi } from './sMSSubscribersApi';
export * from './servicesApi';
import { ServicesApi } from './servicesApi';
export * from './shopifyTerminalApi';
import { ShopifyTerminalApi } from './shopifyTerminalApi';
export * from './shortLinksApi';
import { ShortLinksApi } from './shortLinksApi';
export * from './staticVoucherCampaignsApi';
import { StaticVoucherCampaignsApi } from './staticVoucherCampaignsApi';
export * from './staticVouchersApi';
import { StaticVouchersApi } from './staticVouchersApi';
export * from './systemApi';
import { SystemApi } from './systemApi';
export * from './ticketsApi';
import { TicketsApi } from './ticketsApi';
export * from './videosApi';
import { VideosApi } from './videosApi';
export * from './virtualBusinessCardApi';
import { VirtualBusinessCardApi } from './virtualBusinessCardApi';
export * from './walletConfigurationApi';
import { WalletConfigurationApi } from './walletConfigurationApi';
export * from './walletMobileTerminalApi';
import { WalletMobileTerminalApi } from './walletMobileTerminalApi';
export * from './walletTransactionLedgerApi';
import { WalletTransactionLedgerApi } from './walletTransactionLedgerApi';
export * from './walletWebTerminalApi';
import { WalletWebTerminalApi } from './walletWebTerminalApi';
export * from './wixTerminalApi';
import { WixTerminalApi } from './wixTerminalApi';
export * from './wooCommerceTerminalApi';
import { WooCommerceTerminalApi } from './wooCommerceTerminalApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [APIKeysApi, AmenitiesApi, AnalyticsApi, AppToPersonA2PRegistrationApi, AppleWalletSubscribersApi, AuthenticationApi, BillingPaymentsApi, ClubMembersApi, CountriesApi, CustomerApi, DashboardSummariesApi, DiningApi, DynamicVouchersApi, EmailSubscribersApi, EmployeesApi, GalleryApi, GamingApi, IndustriesApi, InfoGenesisReportsApi, InteractionsApi, LoungeApi, MembershipTiersApi, MerchantApi, MerchantCreditsApi, NewsApi, OpenAIApi, PaymentDesignsApi, PerformancesApi, PointOfSaleConfigurationApi, PrizesApi, ProductsApi, PromotionCodesApi, QRCodeDesignsApi, QuickLinksApi, QuickLinksSectionApi, RoomRatesApi, SMSOperationsApi, SMSSubscribersApi, ServicesApi, ShopifyTerminalApi, ShortLinksApi, StaticVoucherCampaignsApi, StaticVouchersApi, SystemApi, TicketsApi, VideosApi, VirtualBusinessCardApi, WalletConfigurationApi, WalletMobileTerminalApi, WalletTransactionLedgerApi, WalletWebTerminalApi, WixTerminalApi, WooCommerceTerminalApi];
